"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let myName = "sahil";
let myAge = 26;
let isLearningTS = true;
let skills = ["js", "react", "nodejs"];
console.log(myName);
console.log(myAge);
console.log(isLearningTS);
console.log(skills);
